# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rental_pb2 as rental__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rental_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RentalServiceStub:
    """Textbook Rental Hub - protocol contract (Person 2).
    Field names mirror the Person 1 data classes (Book, Rental, RentalResult).

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RentBook = channel.unary_unary(
                '/rental.RentalService/RentBook',
                request_serializer=rental__pb2.BookRequest.SerializeToString,
                response_deserializer=rental__pb2.RentalResponse.FromString,
                _registered_method=True)
        self.SearchBooks = channel.unary_unary(
                '/rental.RentalService/SearchBooks',
                request_serializer=rental__pb2.SearchRequest.SerializeToString,
                response_deserializer=rental__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.CheckStock = channel.unary_unary(
                '/rental.RentalService/CheckStock',
                request_serializer=rental__pb2.StockRequest.SerializeToString,
                response_deserializer=rental__pb2.StockResponse.FromString,
                _registered_method=True)
        self.ListActiveRentals = channel.unary_unary(
                '/rental.RentalService/ListActiveRentals',
                request_serializer=rental__pb2.RentalsRequest.SerializeToString,
                response_deserializer=rental__pb2.RentalsResponse.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/rental.RentalService/ReturnBook',
                request_serializer=rental__pb2.ReturnRequest.SerializeToString,
                response_deserializer=rental__pb2.RentalResponse.FromString,
                _registered_method=True)


class RentalServiceServicer:
    """Textbook Rental Hub - protocol contract (Person 2).
    Field names mirror the Person 1 data classes (Book, Rental, RentalResult).

    """

    def RentBook(self, request, context):
        """Required blocking checkout call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBooks(self, request, context):
        """Used by Person 3 for the concurrent student searches.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActiveRentals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Optional feature.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RentalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RentBook': grpc.unary_unary_rpc_method_handler(
                    servicer.RentBook,
                    request_deserializer=rental__pb2.BookRequest.FromString,
                    response_serializer=rental__pb2.RentalResponse.SerializeToString,
            ),
            'SearchBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBooks,
                    request_deserializer=rental__pb2.SearchRequest.FromString,
                    response_serializer=rental__pb2.SearchResponse.SerializeToString,
            ),
            'CheckStock': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStock,
                    request_deserializer=rental__pb2.StockRequest.FromString,
                    response_serializer=rental__pb2.StockResponse.SerializeToString,
            ),
            'ListActiveRentals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActiveRentals,
                    request_deserializer=rental__pb2.RentalsRequest.FromString,
                    response_serializer=rental__pb2.RentalsResponse.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=rental__pb2.ReturnRequest.FromString,
                    response_serializer=rental__pb2.RentalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rental.RentalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rental.RentalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RentalService:
    """Textbook Rental Hub - protocol contract (Person 2).
    Field names mirror the Person 1 data classes (Book, Rental, RentalResult).

    """

    @staticmethod
    def RentBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/RentBook',
            rental__pb2.BookRequest.SerializeToString,
            rental__pb2.RentalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/SearchBooks',
            rental__pb2.SearchRequest.SerializeToString,
            rental__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/CheckStock',
            rental__pb2.StockRequest.SerializeToString,
            rental__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActiveRentals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/ListActiveRentals',
            rental__pb2.RentalsRequest.SerializeToString,
            rental__pb2.RentalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.RentalService/ReturnBook',
            rental__pb2.ReturnRequest.SerializeToString,
            rental__pb2.RentalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
