# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rental.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rental.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crental.proto\x12\x06rental\"D\n\x04\x42ook\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\r\n\x05stock\x18\x04 \x01(\x05\"O\n\x06Rental\x12\x11\n\trental_id\x18\x01 \x01(\t\x12\x12\n\nstudent_id\x18\x02 \x01(\t\x12\x0f\n\x07\x62ook_id\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\"2\n\x0b\x42ookRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62ook_id\x18\x02 \x01(\t\"^\n\x0eRentalResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\trental_id\x18\x03 \x01(\t\x12\x17\n\x0fremaining_stock\x18\x04 \x01(\x05\"\"\n\rReturnRequest\x12\x11\n\trental_id\x18\x01 \x01(\t\" \n\rSearchRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"-\n\x0eSearchResponse\x12\x1b\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0c.rental.Book\"\x1f\n\x0cStockRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\">\n\rStockResponse\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\r\n\x05\x66ound\x18\x03 \x01(\x08\"$\n\x0eRentalsRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\"2\n\x0fRentalsResponse\x12\x1f\n\x07rentals\x18\x01 \x03(\x0b\x32\x0e.rental.Rental2\xc4\x02\n\rRentalService\x12\x37\n\x08RentBook\x12\x13.rental.BookRequest\x1a\x16.rental.RentalResponse\x12<\n\x0bSearchBooks\x12\x15.rental.SearchRequest\x1a\x16.rental.SearchResponse\x12\x39\n\nCheckStock\x12\x14.rental.StockRequest\x1a\x15.rental.StockResponse\x12\x44\n\x11ListActiveRentals\x12\x16.rental.RentalsRequest\x1a\x17.rental.RentalsResponse\x12;\n\nReturnBook\x12\x15.rental.ReturnRequest\x1a\x16.rental.RentalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rental_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=24
  _globals['_BOOK']._serialized_end=92
  _globals['_RENTAL']._serialized_start=94
  _globals['_RENTAL']._serialized_end=173
  _globals['_BOOKREQUEST']._serialized_start=175
  _globals['_BOOKREQUEST']._serialized_end=225
  _globals['_RENTALRESPONSE']._serialized_start=227
  _globals['_RENTALRESPONSE']._serialized_end=321
  _globals['_RETURNREQUEST']._serialized_start=323
  _globals['_RETURNREQUEST']._serialized_end=357
  _globals['_SEARCHREQUEST']._serialized_start=359
  _globals['_SEARCHREQUEST']._serialized_end=391
  _globals['_SEARCHRESPONSE']._serialized_start=393
  _globals['_SEARCHRESPONSE']._serialized_end=438
  _globals['_STOCKREQUEST']._serialized_start=440
  _globals['_STOCKREQUEST']._serialized_end=471
  _globals['_STOCKRESPONSE']._serialized_start=473
  _globals['_STOCKRESPONSE']._serialized_end=535
  _globals['_RENTALSREQUEST']._serialized_start=537
  _globals['_RENTALSREQUEST']._serialized_end=573
  _globals['_RENTALSRESPONSE']._serialized_start=575
  _globals['_RENTALSRESPONSE']._serialized_end=625
  _globals['_RENTALSERVICE']._serialized_start=628
  _globals['_RENTALSERVICE']._serialized_end=952
# @@protoc_insertion_point(module_scope)
